spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  # Bus消息总线向rabbitmq发送yml配置已更新，需要rabbitmq再向三个业务服务发送消息通知让它们远程连接git更新配置
  rabbitmq:
    host: 192.168.64.100
    port: 5672
    username: admin
    password: admin
    virtual-host: roy-virtual-host-test

  zipkin:
    sender:
      type: rabbit

# 8001   8101   8201
server:
  port: 8201

eureka:
  client:
    service-url:
      # 可以从云服务商购买不同地点的eureka服务器
      # 自己的服务器只能写 defaultZone
      defaultZone: http://eureka1:2001/eureka

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2