# application.yml
# yml - yaml - yet another markup language
# 腋毛

# 向注册中心注册的名字
spring:
  application:
    name: item-service


# item    8001
# user    8101
# order   8201
server:
  port: 8002


eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

