spring:
  application:
    name: config-server

# 配置在git，配置git的url
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Mio-Luo/springcloud1
          search-paths: /config

server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka